Repository NHSDigital/im1-pfs-auth, pull requests merged in 2025-08, with the labels that each got.

#19 NPA-5247: Partly Refine Readme
  README.md
  docs/developer-guides/CODE_OF_CONDUCT.md
  docs/developer-guides/CONTRIBUTING.md
  scripts/config/vale/styles/config/vocabularies/words/accept.txt
Labels: documentation

#21 NPA-5236: Add Implementation to authentication endpoint
  .github/actions/build-container/action.yaml
  .github/workflows/pull-request-checks.yml
  .github/workflows/reusable-core-code-checks.yml
  .github/workflows/reusable-deploy.yml
  Makefile
  README.md
  app/Dockerfile
  app/api/app.py
  app/api/application/__init__.py
  app/api/application/forward_request.py
  app/api/application/jwt.py
  app/api/application/tests/__init__.py
  app/api/application/tests/test_forward_request.py
  app/api/application/tests/test_jwt.py
  app/api/domain/__init__.py
  app/api/domain/base_client.py
  app/api/domain/exception.py
  app/api/domain/forward_request_model.py
  app/api/domain/forward_response_model.py
  app/api/domain/tests/__init__.py
  app/api/domain/tests/test_forward_request_model.py
  app/api/domain/tests/test_forward_response_model.py
  app/api/infrastructure/__init__.py
  app/api/infrastructure/data/mocked_emis_response.json
  app/api/infrastructure/emis_client.py
  app/api/infrastructure/tests/__init__.py
  app/api/infrastructure/tests/test_emis_client.py
  app/api/tests/test_app.py
  app/pyproject.toml
  app/uv.lock
  docs/user-guides/Deploy_To_Apigee.md
  openapitools.json
  pyproject.toml
  specification/examples/errors.yaml
  specification/im1-pfs-auth-api.yaml
  uv.lock
Labels: documentation, enhancement, dependencies, github_actions

#31 NPA-5246: Restrict to Trusted Client
  app/api/app.py
  sandbox/api/authentication.py
  sandbox/api/tests/test_app.py
  specification/x-nhsd-apim/x-nhsd-apim-internal-dev.yaml
Labels: enhancement

#33 NPA-5244: Add End to End Test Framework
  .github/actions/check-uv-lock/action.yaml
  .github/actions/create-lines-of-code-report/action.yaml
  .github/actions/ruff-checks/action.yaml
  .github/actions/ruff-format/action.yaml
  .github/actions/run-end-to-end-tests/action.yaml
  .github/actions/run-unit-tests/action.yaml
  .github/actions/scan-dependencies/action.yaml
  .github/actions/setup-python-dependencies/action.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/reusable-additional-code-checks.yml
  .github/workflows/reusable-core-code-checks.yml
  .github/workflows/reusable-deploy.yml
  .gitignore
  .tool-versions
  Makefile
  README.md
  app/Dockerfile
  app/api/app.py
  app/api/application/forward_request.py
  app/api/application/jwt.py
  app/api/application/tests/test_jwt.py
  app/api/domain/base_client.py
  app/api/domain/forward_request_model.py
  app/api/domain/forward_response_model.py
  app/api/infrastructure/emis_client.py
  app/api/infrastructure/tests/test_emis_client.py
  app/api/tests/test_app.py
  app/pyproject.toml
  app/uv.lock
  pyproject.toml
  sandbox/Dockerfile
  scripts/config/portman/portman-cli.json
  tests/__init__.py
  tests/end_to_end/__init__.py
  tests/end_to_end/authentication/POST/__init__.py
  tests/end_to_end/authentication/POST/conftest.py
  tests/end_to_end/authentication/POST/test_200.py
  tests/end_to_end/authentication/__init__.py
  tests/end_to_end/utils/__init__.py
  tests/end_to_end/utils/apigee_authentication.py
  uv.lock
Labels: documentation, enhancement

#37 NPA-5365: Add Environments Documentation
  docs/user-guides/Environments.md
Labels: documentation, enhancement
